sonar.projectKey=tech-challenge-workshop_work-order-service
sonar.organization=tech-challenge-workshop
sonar.sources=src
sonar.tests=tests
sonar.exclusions=src/generated/**,**/*.module.ts,src/main.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info
